// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMSzXMC54fFe-9_w12JZrhYDJHaySE2Rs',
    appId: '1:628620288554:web:33e9ebcd6abd2cf7df1953',
    messagingSenderId: '628620288554',
    projectId: 'segar-radios',
    authDomain: 'segar-radios.firebaseapp.com',
    storageBucket: 'segar-radios.appspot.com',
    measurementId: 'G-23G7241F7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBNN_wxpFcMli7UHLZgZwg7rppRja1MQ',
    appId: '1:628620288554:android:600b180cab425fa6df1953',
    messagingSenderId: '628620288554',
    projectId: 'segar-radios',
    storageBucket: 'segar-radios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqYVlYvfv1QmQeKR27Mx61H8AYMSk0Pr0',
    appId: '1:628620288554:ios:fa82b29ff12b7108df1953',
    messagingSenderId: '628620288554',
    projectId: 'segar-radios',
    storageBucket: 'segar-radios.appspot.com',
    iosBundleId: 'com.segar.segarRadios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqYVlYvfv1QmQeKR27Mx61H8AYMSk0Pr0',
    appId: '1:628620288554:ios:fa82b29ff12b7108df1953',
    messagingSenderId: '628620288554',
    projectId: 'segar-radios',
    storageBucket: 'segar-radios.appspot.com',
    iosBundleId: 'com.segar.segarRadios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMSzXMC54fFe-9_w12JZrhYDJHaySE2Rs',
    appId: '1:628620288554:web:901dd3271b736670df1953',
    messagingSenderId: '628620288554',
    projectId: 'segar-radios',
    authDomain: 'segar-radios.firebaseapp.com',
    storageBucket: 'segar-radios.appspot.com',
    measurementId: 'G-RM09QK7N27',
  );
}
